version: '3.3'

services:
  bot:
    container_name: homework_geektech
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/services/bot/homework-geektech
